### ISSUE TITLE
Delayed animations only trigger when scrolling in down direction

### ISSUE THREAD

**Issue by Invincibear** [jasielmacedo/hatcss#1]
Hey man, love the work you've done here, thank you!!!
Your implementation of delayed animations resolved some laggy mobile animation issues I unfortunately wasted hours unsuccessfully fixing using alternative solutions.

I noticed that in scenarios where a page is refreshed lower down or jumped to somewhere farther down , scrolling up does not trigger elements with `.animate_when_almost_visible`. Is there any way to have bidirectional scrolling detection?

Also, how would you go about resetting animations of elements once they've been scrolled past and are out of view? I want to re-animate the green call buttons on this page so that every time they're seen they play their animation, not just one time: [http://driving-school-surrey.ca/](http://driving-school-surrey.ca/)

**Comment by jasielmacedo** [comment]
Hi @Invincibear 
For the first one, unfortunately my solution is based on [Waypoint ](http://imakewebthings.com/waypoints/guides/jquery-zepto/) concept. The browser scroll act like a timeline (Up to Down)  and each class element act like a keyframe on timeline. In this scenario where a page is refreshed lower down or like you said jumped to somewhere farther down, it means that the user already seen the content before the viewport area. 
I will try to solve, but maybe you can see the [Waypoint ](http://imakewebthings.com/waypoints/guides/jquery-zepto/) api to try to create you own solution if you want.

**Comment by jasielmacedo** [comment]
Hey @Invincibear i created a simple solution for that.
Add the class **repeat_animation** to repeat when the scroll up
Just check the example and readme for more info.
I hope this can be useful for you.
